parameters:
    xsolve.cookie_acknowledgement_bar.service.class: Yproximite\Bundle\CookieAcknowledgement\Service\CookieAcknowledgementService
    xsolve.cookie_acknowledgement_bar.event_listener.class: Yproximite\Bundle\CookieAcknowledgement\EventListener\CookieAcknowledgementBarListener

services:
    xsolve.cookie_acknowledgement_bar.service:
        class: "%xsolve.cookie_acknowledgement_bar.service.class%"
        arguments:    ["@templating", "%xsolve.cookie_acknowledgement_bar.template%"]
